<link rel="stylesheet" href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css">
<link rel="stylesheet" href="https://kit.fontawesome.com/a2dd6045c4.js">
<link rel="stylesheet" href="./css/estiloCartilla/cartillaLadoNavegacion.css">
<link rel="stylesheet" href="./css/estiloEmpleados/empleadosPrincipal.css">
<link rel="stylesheet" href="./css/estiloIngresos/ingresoPanel.css">
<link rel="stylesheet" href="./css/estiloIngresos/ingresoPrincipal.css">
<link rel="stylesheet" href="./css/estiloPlazas/plazasAside.css">
<link rel="stylesheet" href="./css/estiloPlazas/plazasMaquetacion.css">
<link rel="stylesheet" href="./css/estiloPlazas/plazasPrincipal.css">
<link rel="stylesheet" href="./css/estiloUsuarioAdmin/usuariosAdminPrincipal.css">
